[package]
name = "CHALLENGE_01"
version = "0.1.0"
authors = ["Aibhstin <pickfora@uni.coventry.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.3.1"
base64 = "0.12.2"
